import type { Metadata } from "next";
import { Geist, Geist_Mono, Noto_Kufi_Arabic } from "next/font/google";
import { ToastContainer } from "react-toastify";

import "./globals.css";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const kufiArabic = Noto_Kufi_Arabic({
  variable: "--font-Noto_Kufi_Arabic",

  subsets: ["arabic"],
  weight: ["300", "400", "500"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Cloud Hosting",
  description: "Generated by create next app",
};
interface RouteLayoutProps {
  children: React.ReactNode;
}
export default function RootLayout({ children }: RouteLayoutProps) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${kufiArabic.variable} antialiased`}
      >
        <Header></Header>
        <ToastContainer theme="colored" position="top-center" />
        <main>{children}</main>
        <Footer></Footer>
      </body>
    </html>
  );
}
